%% Curvature Comb Modes Demo using yatch\_offset3.dat
% Reconstruct the hull, then showcase curve, surface, and section combs.
% Copyright (c) 2008-2025 Ahmad Faisal Mohamad Ayob, VSG Labs

close all;
clc;

rawOffsets = load(fullfile('data', 'yatch_offset3.dat'));
stationData = xyz2station(rawOffsets);

[cpX, cpY, cpZ, stationMSE, waterlineMSE] = BSplineFit3(6, 6, stationData);
fprintf('Station MSE: %.4f, Waterline MSE: %.4f\n', stationMSE, waterlineMSE);

[~, ~, surfaceData] = analyzeSmoothness(cpX, cpY, cpZ);

colormapChoice = parula(256);

fig = figure('Name', 'Curvature Comb Modes', 'Position', [100 100 1400 480]);
t = tiledlayout(fig, 1, 3, 'TileSpacing', 'compact', 'Padding', 'compact');

% Mode 1: Curves (single station curve)
ax1 = nexttile(t, 1);
stationIdx = round(numel(stationData) / 2);
stationCurve = [stationData(stationIdx).x', ...
                stationData(stationIdx).y', ...
                stationData(stationIdx).z'];
plotCurveCurvatureComb(stationCurve, ...
    'Axes', ax1, ...
    'CombSpacing', 8, ...
    'CombColormap', colormapChoice, ...
    'CurveLineWidth', 2.0);
view(ax1, [90 0]);
axis(ax1, 'equal');
ax1.Title.String = sprintf('Mode 1: Curve Comb (Station %d)', stationIdx);
ax1.Box = 'on';

% Mode 2: Surface edges and isoparms
ax2 = nexttile(t, 2);
plotCurvatureCombs(surfaceData, ...
    'Direction', 'both', ...
    'NumCurves', 6, ...
    'IncludeEdges', true, ...
    'CombSpacing', 6, ...
    'SurfaceAlpha', 0.18, ...
    'CombColormap', colormapChoice, ...
    'BaseCurveLineWidth', 1.5, ...
    'CombLineWidth', 1.6);
view(ax2, [-35 20]);
ax2.Title.String = 'Mode 2: Surface Edges & Iso-params';
ax2.Box = 'on';

% Mode 3: Section lines through the surface (x-axis sections)
ax3 = nexttile(t, 3);
xVals = surfaceData.points(:, :, 1);
sectionX = linspace(min(xVals, [], 'all'), max(xVals, [], 'all'), 5);
sectionX = sectionX(2:4);
plotSectionCurvatureCombs(surfaceData, ...
    'Axis', 'x', ...
    'Values', sectionX, ...
    'Axes', ax3, ...
    'CombSpacing', 6, ...
    'SurfaceAlpha', 0.08, ...
    'CombColormap', colormapChoice, ...
    'CurveLineWidth', 1.8, ...
    'CombLineWidth', 1.5);
view(ax3, [-35 20]);
ax3.Title.String = 'Mode 3: Section Planes';
ax3.Box = 'on';

title(t, 'Curvature Comb Modes for Reconstructed Hull');
